[pytest]
filterwarnings =
    # 完全屏蔽 setuptools 的 DeprecationWarning
    ignore:.*pkg_resources.*:DeprecationWarning
    # 完全屏蔽 pytest-html 的 DeprecationWarning
    ignore:.*pytest_html.*:DeprecationWarning
    # 完全屏蔽 airtest 的 UserWarning
    ignore:.*airtest.*:UserWarning
    ignore:.*ADB screenshots.*:UserWarning
    ignore:.*report\.extra.*deprecated.*:DeprecationWarning